name: Automatically publish to CurseForge
on:
  release:
    types: [published]
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
      - name: Write manifest
        run: sed -i 's/%MODPACK_VERSION%/${{ steps.get_release.outputs.tag_name }}/g' manifest.json
      - name: Zip Modpack
        run: zip -r modpack.zip *
      - name: Read Changelog
        id: read_changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./changelog.md
      - name: Get Release Type
        id: get_curseforge_release_type
        run: |
          RELEASE_TYPE=$(echo ${{ steps.get_release.outputs.name }} | grep -oE '\[(.*)\]' | sed 's/[][]//g')
          echo ::set-output name=release_type::$RELEASE_TYPE
      - name: Copy files for CurseForge upload
        run: |
          mkdir -p curse_upload
          cp ./modpack.zip './curse_upload/StalkersRoom-${{ steps.get_release.outputs.tag_name }}.zip'
      - name: Upload to CurseForge
        uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
        with:
          api-token: ${{ secrets.CF_API_TOKEN }}
          project-id: '893217'
          modpack-path: './curse_upload/StalkersRoom-${{ steps.get_release.outputs.tag_name }}.zip'
          changelog: ${{ steps.read_changelog.outputs.content }}
          changelog-format: 'markdown'
          game-version: ${{ vars.MC_VERSION }}
          display-name: 'Stalkers Room ${{ steps.get_release.outputs.tag_name }}'
          release-type: ${{ steps.get_curseforge_release_type.outputs.release_type }}
      - name: Upload Modpack
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./modpack.zip
          asset_name: 'StalkersRoom-${{ steps.get_release.outputs.tag_name }}.zip'
          asset_content_type: application/zip
