name: Automatically publish to CurseForge
on:
  release:
    types: [published]
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
      - name: Write manifest
        run: sed -i 's/%MODPACK_VERSION%/${{ steps.get_release.outputs.tag_name }}/g' manifest.json
      - name: Zip Modpack
        run: zip -r modpack.zip *
      - name: Copy files for CurseForge upload
        run: |
          mkdir -p curse_upload
          cp ./modpack.zip './curse_upload/StalkersRoom-${{ steps.get_release.outputs.tag_name }}.zip'
      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
         name: 'Stalkers Room ${{ steps.get_release.outputs.tag_name }} for ${{ vars.MC_VERSION }}'
         curseforge-id: 893217
         curseforge-token: ${{ secrets.CF_API_TOKEN }}
         files: './curse_upload/StalkersRoom-${{ steps.get_release.outputs.tag_name }}.zip'
         loaders: forge
         game-versions: ${{ vars.MC_VERSION }}
         changelog-file: ./changelog.md
      - name: Upload Modpack
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./modpack.zip
          asset_name: 'StalkersRoom-${{ steps.get_release.outputs.tag_name }}.zip'
          asset_content_type: application/zip
