on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "changelog.md"
          token: ${{ secrets.GH_TOKEN }}
